# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EspressoGUI(object):
    def setupUi(self, EspressoGUI):
        EspressoGUI.setObjectName("EspressoGUI")
        EspressoGUI.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EspressoGUI.sizePolicy().hasHeightForWidth())
        EspressoGUI.setSizePolicy(sizePolicy)
        EspressoGUI.setMinimumSize(QtCore.QSize(1920, 1080))
        EspressoGUI.setMaximumSize(QtCore.QSize(1920, 1080))
        EspressoGUI.setStyleSheet("background-color: #FFFFFF;")
        EspressoGUI.setInputMethodHints(QtCore.Qt.InputMethodHints.ImhDigitsOnly)
        self.centralwidget = QtWidgets.QWidget(EspressoGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1024, 768))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setMaximumSize(QtCore.QSize(350, 16777215))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.flushButton = QtWidgets.QPushButton(self.verticalWidget)
        self.flushButton.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.flushButton.setFont(font)
        self.flushButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-color: #343434;\n"
"border-width: 5px;\n"
"border-radius: 10px;\n"
"}")
        self.flushButton.setCheckable(True)
        self.flushButton.setObjectName("flushButton")
        self.verticalLayout_2.addWidget(self.flushButton)
        self.steamButton = QtWidgets.QPushButton(self.verticalWidget)
        self.steamButton.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.steamButton.setFont(font)
        self.steamButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-color: #343434;\n"
"border-width: 5px;\n"
"border-radius: 10px;\n"
"}")
        self.steamButton.setObjectName("steamButton")
        self.verticalLayout_2.addWidget(self.steamButton)
        self.manualButton = QtWidgets.QPushButton(self.verticalWidget)
        self.manualButton.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.manualButton.setFont(font)
        self.manualButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-color: #343434;\n"
"border-width: 5px;\n"
"border-radius: 10px;\n"
"}")
        self.manualButton.setCheckable(True)
        self.manualButton.setObjectName("manualButton")
        self.verticalLayout_2.addWidget(self.manualButton)
        self.modeList = QtWidgets.QListWidget(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.modeList.setFont(font)
        self.modeList.setObjectName("modeList")
        self.verticalLayout_2.addWidget(self.modeList)
        self.saveButton = QtWidgets.QPushButton(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-color: #343434;\n"
"border-width: 5px;\n"
"border-radius: 10px;\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_2.addWidget(self.saveButton)
        self.gridWidget = QtWidgets.QWidget(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridWidget.sizePolicy().hasHeightForWidth())
        self.gridWidget.setSizePolicy(sizePolicy)
        self.gridWidget.setMaximumSize(QtCore.QSize(220, 16777215))
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2.addWidget(self.gridWidget)
        self.horizontalLayout.addWidget(self.verticalWidget)
        self.plotLayout = QtWidgets.QVBoxLayout()
        self.plotLayout.setObjectName("plotLayout")
        self.horizontalLayout.addLayout(self.plotLayout)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout.addWidget(self.line_5)
        self.verticalWidget1 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget1.sizePolicy().hasHeightForWidth())
        self.verticalWidget1.setSizePolicy(sizePolicy)
        self.verticalWidget1.setMinimumSize(QtCore.QSize(250, 0))
        self.verticalWidget1.setMaximumSize(QtCore.QSize(220, 16777215))
        self.verticalWidget1.setObjectName("verticalWidget1")
        self.PlotLayout = QtWidgets.QVBoxLayout(self.verticalWidget1)
        self.PlotLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.PlotLayout.setObjectName("PlotLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.tempBox = QtWidgets.QDoubleSpinBox(self.verticalWidget1)
        self.tempBox.setMinimumSize(QtCore.QSize(150, 120))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tempBox.setFont(font)
        self.tempBox.setMaximum(100.0)
        self.tempBox.setObjectName("tempBox")
        self.gridLayout.addWidget(self.tempBox, 6, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.presPushButton = QtWidgets.QPushButton(self.verticalWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presPushButton.sizePolicy().hasHeightForWidth())
        self.presPushButton.setSizePolicy(sizePolicy)
        self.presPushButton.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.presPushButton.setFont(font)
        self.presPushButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-color: #343434;\n"
"border-width: 5px;\n"
"border-radius: 20px;\n"
"}")
        self.presPushButton.setCheckable(True)
        self.presPushButton.setObjectName("presPushButton")
        self.gridLayout_2.addWidget(self.presPushButton, 2, 0, 1, 1)
        self.flowPushButton = QtWidgets.QPushButton(self.verticalWidget1)
        self.flowPushButton.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.flowPushButton.setFont(font)
        self.flowPushButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-color: #343434;\n"
"border-width: 5px;\n"
"border-radius: 20px;\n"
"}")
        self.flowPushButton.setCheckable(True)
        self.flowPushButton.setObjectName("flowPushButton")
        self.gridLayout_2.addWidget(self.flowPushButton, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.pressureSlider = QtWidgets.QSlider(self.verticalWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressureSlider.sizePolicy().hasHeightForWidth())
        self.pressureSlider.setSizePolicy(sizePolicy)
        self.pressureSlider.setMinimumSize(QtCore.QSize(0, 500))
        self.pressureSlider.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.pressureSlider.setAutoFillBackground(False)
        self.pressureSlider.setStyleSheet("\n"
"QSlider::groove:vertical { \n"
"    border: 5px solid #424242; \n"
"    height: 450px; \n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"QSlider::handle:vertical { \n"
"    background-color: #343434; \n"
"    border: 10px #343434; \n"
"    width: 40px; \n"
"    height: 150px; \n"
"    line-height: 20px; \n"
"    margin-top: -5px; \n"
"    margin-bottom: -5px; \n"
"    border-radius: 25px; \n"
"}")
        self.pressureSlider.setMaximum(100)
        self.pressureSlider.setPageStep(1)
        self.pressureSlider.setOrientation(QtCore.Qt.Orientations.Vertical)
        self.pressureSlider.setInvertedAppearance(False)
        self.pressureSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksAbove)
        self.pressureSlider.setTickInterval(10)
        self.pressureSlider.setObjectName("pressureSlider")
        self.gridLayout.addWidget(self.pressureSlider, 4, 0, 1, 1)
        self.pressureText = QtWidgets.QLabel(self.verticalWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressureText.sizePolicy().hasHeightForWidth())
        self.pressureText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pressureText.setFont(font)
        self.pressureText.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.pressureText.setObjectName("pressureText")
        self.gridLayout.addWidget(self.pressureText, 5, 0, 1, 1)
        self.startButton = QtWidgets.QPushButton(self.verticalWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(220, 180))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.startButton.setFont(font)
        self.startButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.startButton.setStyleSheet("QPushButton{\n"
"border-style: solid;\n"
"border-color: #343434;\n"
"border-width: 5px;\n"
"border-radius: 40px;\n"
"}")
        self.startButton.setCheckable(True)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 0, 0, 1, 1)
        self.PlotLayout.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.verticalWidget1)
        EspressoGUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(EspressoGUI)
        self.statusbar.setObjectName("statusbar")
        EspressoGUI.setStatusBar(self.statusbar)

        self.retranslateUi(EspressoGUI)
        QtCore.QMetaObject.connectSlotsByName(EspressoGUI)

    def retranslateUi(self, EspressoGUI):
        _translate = QtCore.QCoreApplication.translate
        EspressoGUI.setWindowTitle(_translate("EspressoGUI", "Plotter"))
        self.flushButton.setText(_translate("EspressoGUI", "Flush"))
        self.steamButton.setText(_translate("EspressoGUI", "Steam"))
        self.manualButton.setText(_translate("EspressoGUI", "Manual"))
        self.saveButton.setText(_translate("EspressoGUI", "Save Plot To CSV"))
        self.presPushButton.setText(_translate("EspressoGUI", "Pressure"))
        self.flowPushButton.setText(_translate("EspressoGUI", "Flow"))
        self.pressureText.setText(_translate("EspressoGUI", "0.0"))
        self.startButton.setText(_translate("EspressoGUI", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EspressoGUI = QtWidgets.QMainWindow()
    ui = Ui_EspressoGUI()
    ui.setupUi(EspressoGUI)
    EspressoGUI.show()
    sys.exit(app.exec())
